[packages.pathogen]
directory = "autoload"
filename = "pathogen.vim"
remote = "https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim"


[packages.oh-my-zsh]
directory = "bundle/oh-my-zsh"
github = { username = "robbyrussell", repository = "oh-my-zsh" }